#ifndef __RHI_VERTEX_LAYOUT_ENUMS_H__
#define __RHI_VERTEX_LAYOUT_ENUMS_H__


// Element Type
enum RhiVertexElementType
{
	RHI_VERTEX_ELEMENT_TYPE_NONE				=	-1,
	RHI_VERTEX_ELEMENT_TYPE_POSITION,
	RHI_VERTEX_ELEMENT_TYPE_COLOR,
	RHI_VERTEX_ELEMENT_TYPE_TEXCOORD0,
	RHI_VERTEX_ELEMENT_TYPE_NORMAL,

	RHI_VERTEX_ELEMENT_TYPE_COUNT
};

// all the supported vertex layout
enum RhiVertexLayoutType
{
	RHI_VERTEX_LAYOUT_INVALID	=	-1,
	RHI_VERTEX_LAYOUT_POSITION_ONLY	=	0,
	RHI_VERTEX_LAYOUT_POSITION_COLOR,
	RHI_VERTEX_LAYOUT_SPRITES,
	RHI_VERTEX_LAYOUT_BASIC_LIT,

	RHI_VERTEX_LAYOUT_COUNT
};

// Key Id to identify a VertexLayout
enum RhiVertexLayoutTypeKey
{
	RHI_VERTEX_FORMAT_KEY_POSITION_ONLY		=	1,
	RHI_VERTEX_FORMAT_KEY_POSITION_COLORED	=	3,
	RHI_VERTEX_FORMAT_KEY_SPRITES			=	7,	

	RHI_VERTEX_FORMAT_KEY_BASIC_LIT			=	9,	
};


#endif