#ifndef __JSON_ENUM_H__
#define __JSON_ENUM_H__

enum JSonPropertyType
{
	JSON_PROPERTY_TYPE_NONE = -1,
	JSON_PROPERTY_TYPE_BOOL	=	0,
	JSON_PROPERTY_TYPE_INT,
	JSON_PROPERTY_TYPE_FLOAT,
	JSON_PROPERTY_TYPE_STRING,
	JSON_PROPERTY_TYPE_NODE,

	JSON_PROPERTY_TYPE_INT_ARRAY,
	JSON_PROPERTY_TYPE_FLOAT_ARRAY,
	JSON_PROPERTY_TYPE_NODE_ARRAY,


	JSON_PROPERTY_TYPE_ARRAY,
	JSON_PROPERTY_TYPE_INT32,
	JSON_PROPERTY_TYPE_INT64,
	JSON_PROPERTY_TYPE_DOUBLE,

};

#endif